site_name: mac-dev-setup
theme:
    favicon: https://juftin.com/favicon.ico
    logo: https://raw.githubusercontent.com/juftin/juftin/main/static/juftin.png
    name: material
    features:
        - navigation.tracking
        - content.code.annotate
        - content.code.copy
    palette:
        - media: "(prefers-color-scheme: light)"
          scheme: default
          accent: purple
          toggle:
              icon: material/weather-sunny
              name: Switch to dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: black
          toggle:
              icon: material/weather-night
              name: Switch to light mode
repo_url: https://github.com/juftin/mac-dev-setup/
repo_name: mac-dev-setup
edit_uri: blob/main/docs/
site_author: juftin
remote_branch: gh-pages
nav:
    - index.md
    - startup.md
    - terminal.md
    - python.md
    - git.md
    - apps.md
    - silicon.md
    - aws.md
    - jetbrains.md
    - mac_settings.md
    - productivity.md
    - ssh.md
    - references.md
extra:
    generator: false
exclude_docs: |
    gen_pages.py
    !dot_files/*
markdown_extensions:
    - toc:
          permalink: "#"
    - pymdownx.snippets:
          base_path:
              - !relative $config_dir
    - pymdownx.magiclink
    - attr_list
    - md_in_html
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - markdown.extensions.attr_list
    - pymdownx.keys
    - pymdownx.tasklist
    - pymdownx.tilde
    - admonition
    - callouts
    - pymdownx.details
    - pymdownx.emoji
    - pymdownx.tabbed:
          alternate_style: true
plugins:
    - search
    - gen-files:
          scripts:
              - docs/gen_pages.py
